### PR TITLE
fixing get_sectionId_for_z documentation

### PR DESCRIPTION
**Pull request by djkapner**

### CODE REVIEW

**Comment by RussTorres** [comment]
Isn't this documented correctly (if a little brief)?  You give a z value and it returns a sectionId?

**Comment by djkapner** [comment]
> Isn't this documented correctly (if a little brief)? You give a z value and it returns a sectionId?

The documentation said it returned a `float`. It returns a `str`

**Comment by RussTorres** [comment]
Right, I see I misread that.  The docstring of this and at least one other function also lists sectionId as an input when it is actually z.

**Comment by djkapner** [comment]
I see that. I'll go ahead and fix that in this PR.

**Pull request merged**
